name: build-env2
channels:
  - conda-forge
dependencies:
  - catppuccin-jupyterlab  # Theme extension
  - jupyter_server  # Needed for content
  - jupyterlite-core
  - jupyterlite-pyodide-kernel
  - jupyterlite-terminal
  - jupyterlite-xeus
  - nodejs  # Needed for terminal extension
  - pip:
    - jupyterlite-p5-kernel  # Not available on conda-forge
