name: Build and deploy to github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build the html presentation
        shell: bash -l {0}
        run: |
          npm install
          npm run html

      - name: Deployment 2 install mamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: deploy2/build-environment.yml
          cache-environment: true

      - name: Deployment 2 Build the JupyterLite site
        shell: bash -l {0}
        working-directory: deploy2
        run: |
          jupyter lite build --contents contents --output-dir ../output/deploy2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./output

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
